server:
  port: 8080
spring:
  application:
    name: reggie
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password:
  session:
    # session过期时间 1h
    timeout: 3600s
mybatis-plus:
  # 原生 MyBatis 所支持的配置
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # MyBatis-Plus 全局策略配置
  global-config:
    db-config:
      # 全局默认主键类型
      id-type: ASSIGN_ID
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
# 文件上传路径
reggie:
  path: D:\MyCode\JavaProjects\web\reggie\reggie\img\
sms:
  accessKeyId:
  secret:
  signName:
  templateCode:


